[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ideabank_webapi"
version = "0.0.1"
description = "An API for the services utilized by the Idea Bank application"
readme = "README.md"
requires-python = ">=3.10"
